/**
 * dishes.js — 菜品数据
 */
window.dishData = [
    // 烤鱼类
    { globalId: 101, name: '清江鱼', price: 69, category: '烤鱼类', isDrink: false },
    { globalId: 102, name: '巴沙鱼', price: 49, category: '烤鱼类', isDrink: false },
    { globalId: 103, name: '草鱼', price: 45, category: '烤鱼类', isDrink: false },

    // 汤锅类
    { globalId: 201, name: '铁锅牛蛙小锅', price: 88, category: '汤锅类', isDrink: false },
    { globalId: 202, name: '铁锅牛蛙大锅', price: 118, category: '汤锅类', isDrink: false },
    { globalId: 203, name: '干锅蛙', price: 118, category: '汤锅类', isDrink: false },
    { globalId: 204, name: '干锅鸡', price: 98, category: '汤锅类', isDrink: false },
    { globalId: 205, name: '重庆烧鸡公小锅', price: 78, category: '汤锅类', isDrink: false },
    { globalId: 206, name: '重庆烧鸡公大锅', price: 128, category: '汤锅类', isDrink: false },
    { globalId: 207, name: '甲鱼鸡煲特价', price: 98, category: '汤锅类', isDrink: false },
    { globalId: 208, name: '甲鱼鸡煲中锅', price: 128, category: '汤锅类', isDrink: false },
    { globalId: 209, name: '猪肚鸡小锅', price: 88, category: '汤锅类', isDrink: false },
    { globalId: 210, name: '猪肚鸡大锅', price: 128, category: '汤锅类', isDrink: false },
    { globalId: 211, name: '黑山羊火锅', price: 118, category: '汤锅类', isDrink: false },
    { globalId: 212, name: '美蛙鱼火锅小锅', price: 88, category: '汤锅类', isDrink: false },
    { globalId: 213, name: '美蛙鱼火锅大锅', price: 128, category: '汤锅类', isDrink: false },
    { globalId: 214, name: '酸汤猪蹄小锅', price: 88, category: '汤锅类', isDrink: false },
    { globalId: 215, name: '酸汤猪蹄大锅', price: 138, category: '汤锅类', isDrink: false },
    { globalId: 216, name: '巴蜀腊猪脚小锅', price: 98, category: '汤锅类', isDrink: false },
    { globalId: 217, name: '巴蜀腊猪脚大锅', price: 128, category: '汤锅类', isDrink: false },
    { globalId: 218, name: '肥肠鸡小锅', price: 118, category: '汤锅类', isDrink: false },
    { globalId: 219, name: '肥肠鸡大锅', price: 158, category: '汤锅类', isDrink: false },
    { globalId: 220, name: '肥肠鱼小锅', price: 118, category: '汤锅类', isDrink: false },
    { globalId: 221, name: '肥肠鱼大锅', price: 158, category: '汤锅类', isDrink: false },
    { globalId: 222, name: '酸菜鱼/石锅鱼', price: 88, category: '汤锅类', isDrink: false },
    { globalId: 223, name: '牛腩牛杂煲小锅', price: 88, category: '汤锅类', isDrink: false },
    { globalId: 224, name: '牛腩牛杂煲大锅', price: 138, category: '汤锅类', isDrink: false },
    { globalId: 225, name: '牛排火锅', price: 118, category: '汤锅类', isDrink: false },

    // 配菜类
    { globalId: 301, name: '魔芋', price: 8, category: '配菜类', isDrink: false },
    { globalId: 302, name: '鸭血', price: 8, category: '配菜类', isDrink: false },
    { globalId: 303, name: '黑毛肚', price: 25, category: '配菜类', isDrink: false },
    { globalId: 304, name: '牛肉丸', price: 20, category: '配菜类', isDrink: false },
    { globalId: 305, name: '猪肚', price: 32, category: '配菜类', isDrink: false },
    { globalId: 306, name: '香芋', price: 15, category: '配菜类', isDrink: false },
    { globalId: 307, name: '水豆腐', price: 8, category: '配菜类', isDrink: false },
    { globalId: 308, name: '土豆', price: 8, category: '配菜类', isDrink: false },
    { globalId: 309, name: '玉米', price: 10, category: '配菜类', isDrink: false },
    { globalId: 310, name: '豆皮', price: 12, category: '配菜类', isDrink: false },
    { globalId: 311, name: '冬瓜', price: 8, category: '配菜类', isDrink: false },
    { globalId: 312, name: '淮山', price: 15, category: '配菜类', isDrink: false },
    { globalId: 313, name: '豆芽', price: 6, category: '配菜类', isDrink: false },
    { globalId: 314, name: '莲藕', price: 12, category: '配菜类', isDrink: false },
    { globalId: 315, name: '油麦菜', price: 10, category: '配菜类', isDrink: false },
    { globalId: 316, name: '白萝卜', price: 6, category: '配菜类', isDrink: false },
    { globalId: 317, name: '红薯粉', price: 10, category: '配菜类', isDrink: false },
    { globalId: 318, name: '海带', price: 12, category: '配菜类', isDrink: false },
    { globalId: 319, name: '香菜', price: 12, category: '配菜类', isDrink: false },
    { globalId: 320, name: '生菜', price: 8, category: '配菜类', isDrink: false },
    { globalId: 321, name: '娃娃菜', price: 8, category: '配菜类', isDrink: false },
    { globalId: 322, name: '菠菜', price: 12, category: '配菜类', isDrink: false },
    { globalId: 323, name: '金针菇', price: 12, category: '配菜类', isDrink: false },
    { globalId: 324, name: '香菇', price: 12, category: '配菜类', isDrink: false },
    { globalId: 325, name: '炸腐竹', price: 12, category: '配菜类', isDrink: false },
    { globalId: 326, name: '紫苏', price: 10, category: '配菜类', isDrink: false },

    // 凉菜类
    { globalId: 401, name: '凉拌牛肉', price: 38, category: '凉菜类', isDrink: false },
    { globalId: 402, name: '红油猪耳', price: 30, category: '凉菜类', isDrink: false },
    { globalId: 403, name: '脱骨凤爪', price: 28, category: '凉菜类', isDrink: false },
    { globalId: 404, name: '凉拌折耳根', price: 16, category: '凉菜类', isDrink: false },
    { globalId: 405, name: '卤水拼盘', price: 30, category: '凉菜类', isDrink: false },
    { globalId: 406, name: '凉拌鱼皮', price: 22, category: '凉菜类', isDrink: false },
    { globalId: 407, name: '香辣毛豆', price: 15, category: '凉菜类', isDrink: false },
    { globalId: 408, name: '凉拌皮蛋', price: 12, category: '凉菜类', isDrink: false },
    { globalId: 409, name: '凉拌/芥末秋葵', price: 18, category: '凉菜类', isDrink: false },
    { globalId: 410, name: '刀拍小青瓜', price: 12, category: '凉菜类', isDrink: false },
    { globalId: 411, name: '卤水花生', price: 15, category: '凉菜类', isDrink: false },
    { globalId: 412, name: '酸辣藕带', price: 15, category: '凉菜类', isDrink: false },

    // 主食点心
    { globalId: 501, name: '老妈子炒饭', price: 15, category: '主食点心', isDrink: false },
    { globalId: 502, name: '三丝炒粉/河粉', price: 10, category: '主食点心', isDrink: false },
    { globalId: 503, name: '干炒牛河', price: 28, category: '主食点心', isDrink: false },
    { globalId: 504, name: '南瓜饼', price: 15, category: '主食点心', isDrink: false },
    { globalId: 505, name: '香芋地瓜丸', price: 12, category: '主食点心', isDrink: false },
    { globalId: 506, name: '金银小馒头', price: 15, category: '主食点心', isDrink: false },
    { globalId: 507, name: '脆皮香蕉', price: 16, category: '主食点心', isDrink: false },
    { globalId: 508, name: '香芋卷', price: 15, category: '主食点心', isDrink: false },
    { globalId: 509, name: '虾粥', price: 58, category: '主食点心', isDrink: false },
    { globalId: 510, name: '米饭', price: 2, category: '主食点心', isDrink: false },
    { globalId: 511, name: '皮蛋瘦肉粥', price: 58, category: '主食点心', isDrink: false },

    // 炒菜类
    { globalId: 601, name: '火爆腰花', price: 36, category: '炒菜类', isDrink: false },
    { globalId: 602, name: '青椒回锅肉', price: 35, category: '炒菜类', isDrink: false },
    { globalId: 603, name: '巴蜀小酥肉', price: 32, category: '炒菜类', isDrink: false },
    { globalId: 604, name: '农家小炒肉', price: 38, category: '炒菜类', isDrink: false },
    { globalId: 605, name: '农家梅菜扣肉', price: 38, category: '炒菜类', isDrink: false },
    { globalId: 606, name: '鱼香肉丝', price: 35, category: '炒菜类', isDrink: false },
    { globalId: 607, name: '酸辣鸡杂', price: 32, category: '炒菜类', isDrink: false },
    { globalId: 608, name: '小炒黄牛肉', price: 48, category: '炒菜类', isDrink: false },
    { globalId: 609, name: '椒盐鸭下巴', price: 38, category: '炒菜类', isDrink: false },
    { globalId: 610, name: '孜然羊肉', price: 48, category: '炒菜类', isDrink: false },
    { globalId: 611, name: '青椒肉丝', price: 28, category: '炒菜类', isDrink: false },
    { globalId: 612, name: '鼓椒炒花甲', price: 25, category: '炒菜类', isDrink: false },
    { globalId: 613, name: '香辣田螺', price: 16, category: '炒菜类', isDrink: false },
    { globalId: 614, name: '清炒莴笋丝', price: 18, category: '炒菜类', isDrink: false },
    { globalId: 615, name: '干煸泥鳅', price: 48, category: '炒菜类', isDrink: false },
    { globalId: 616, name: '酸菜肥肠', price: 38, category: '炒菜类', isDrink: false },
    { globalId: 617, name: '蒜蓉菜心', price: 19, category: '炒菜类', isDrink: false },
    { globalId: 618, name: '炒空心菜', price: 19, category: '炒菜类', isDrink: false },
    { globalId: 619, name: '炒油麦菜', price: 19, category: '炒菜类', isDrink: false },
    { globalId: 620, name: '虎皮尖椒', price: 25, category: '炒菜类', isDrink: false },
    { globalId: 621, name: '香煎鸡蛋饼', price: 18, category: '炒菜类', isDrink: false },
    { globalId: 622, name: '手撕包菜', price: 18, category: '炒菜类', isDrink: false },
    { globalId: 623, name: '酸辣土豆丝', price: 15, category: '炒菜类', isDrink: false },
    { globalId: 624, name: '韭菜炒鸡蛋', price: 18, category: '炒菜类', isDrink: false },

    // 干锅铁板
    { globalId: 701, name: '干锅鸡翅虾', price: 48, category: '干锅铁板', isDrink: false },
    { globalId: 702, name: '干锅猪尾', price: 48, category: '干锅铁板', isDrink: false },
    { globalId: 703, name: '干锅香辣虾', price: 48, category: '干锅铁板', isDrink: false },
    { globalId: 704, name: '铁板牛肉', price: 48, category: '干锅铁板', isDrink: false },
    { globalId: 705, name: '干锅肥肠', price: 38, category: '干锅铁板', isDrink: false },
    { globalId: 706, name: '干锅牛杂', price: 38, category: '干锅铁板', isDrink: false },
    { globalId: 707, name: '干锅带皮牛肉', price: 38, category: '干锅铁板', isDrink: false },
    { globalId: 708, name: '干锅腌笋腊肉', price: 38, category: '干锅铁板', isDrink: false },
    { globalId: 709, name: '干锅花菜', price: 22, category: '干锅铁板', isDrink: false },
    { globalId: 710, name: '干锅土豆片', price: 22, category: '干锅铁板', isDrink: false },

    // 啤酒类
    { globalId: 801, name: '哈尔滨冰纯', price: 8, category: '啤酒类', isDrink: true },
    { globalId: 802, name: '漓泉', price: 10, category: '啤酒类', isDrink: true },
    { globalId: 803, name: '金标雪花', price: 10, category: '啤酒类', isDrink: true },
    { globalId: 804, name: '乌苏啤酒', price: 12, category: '啤酒类', isDrink: true },
    { globalId: 805, name: '珠江零度/0度', price: 6, category: '啤酒类', isDrink: true },
    { globalId: 806, name: '百威', price: 10, category: '啤酒类', isDrink: true },

    // 白酒类
    { globalId: 901, name: '小毛铺', price: 20, category: '白酒类', isDrink: true },
    { globalId: 902, name: '金荞大毛铺', price: 88, category: '白酒类', isDrink: true },
    { globalId: 903, name: '小百年糊涂33°/33度', price: 18, category: '白酒类', isDrink: true },
    { globalId: 904, name: '小百年糊涂52°/52度', price: 20, category: '白酒类', isDrink: true },
    { globalId: 905, name: '大百年糊涂33°/33度', price: 88, category: '白酒类', isDrink: true },
    { globalId: 906, name: '大百年糊涂52°/52度', price: 98, category: '白酒类', isDrink: true },
    { globalId: 907, name: '小劲酒', price: 20, category: '白酒类', isDrink: true },
    { globalId: 908, name: '大劲酒', price: 68, category: '白酒类', isDrink: true },
    { globalId: 909, name: '牛栏山', price: 20, category: '白酒类', isDrink: true },
    { globalId: 910, name: '江小白', price: 20, category: '白酒类', isDrink: true },
    { globalId: 911, name: '小郎酒', price: 22, category: '白酒类', isDrink: true },
    { globalId: 912, name: '天龙泉22°', price: 18, category: '白酒类', isDrink: true },
    { globalId: 913, name: '天龙泉28°', price: 20, category: '白酒类', isDrink: true },

    // 饮料类
    { globalId: 1001, name: '小天地壹号', price: 6, category: '饮料类', isDrink: true },
    { globalId: 1002, name: '大天地壹号', price: 20, category: '饮料类', isDrink: true },
    { globalId: 1003, name: '小王老吉', price: 5, category: '饮料类', isDrink: true },
    { globalId: 1004, name: '大王老吉', price: 16, category: '饮料类', isDrink: true },
    { globalId: 1005, name: '小椰汁', price: 5, category: '饮料类', isDrink: true },
    { globalId: 1006, name: '大椰汁', price: 20, category: '饮料类', isDrink: true },
    { globalId: 1007, name: '大橙汁', price: 10, category: '饮料类', isDrink: true },
    { globalId: 1008, name: '小可乐', price: 4, category: '饮料类', isDrink: true },
    { globalId: 1009, name: '大可乐', price: 10, category: '饮料类', isDrink: true },
    { globalId: 1010, name: '小雪碧', price: 4, category: '饮料类', isDrink: true },
    { globalId: 1011, name: '大雪碧', price: 10, category: '饮料类', isDrink: true },
    { globalId: 1012, name: '矿泉水', price: 3, category: '饮料类', isDrink: true }
];
